name: Manifest
description: Build and push a docker manifest to Docker Hub

inputs:
  platforms:
    #  eg [{"platform":"linux/amd64", "runner": "ARM64", "slug": "something-arm64"},{"platform":"linux/arm64", "runner": "ubuntu-latest", "slug": "something-amd64"}]
    description: JSON list of platforms to build for
    type: string
    required: true
  tag:
    description: Docker hub tag to push to
    type: string
    required: true
  repository:
    description: Docker hub repository to push to
    type: string
    required: true
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: composite
  steps:
  - name: Checkout this repo
    uses: actions/checkout@v4
  - name: Generate images list
    id: generate_images_list
    shell: bash
    run: |
      PLATFORMS='${{ inputs.platforms }}'

      # Iterate over the platforms and build the image list
      len=$(echo $PLATFORMS | jq '. | length')
      for ((i=0; i<$len; i++)); do
          slug=$(echo $PLATFORMS | jq -r --argjson i $i '.[$i].slug')
          imagetag="${{ inputs.tag }}-$slug"
          imagetag=$(echo $imagetag | cut -d ':' -f2)
          image="${{ inputs.repository }}:$imagetag"
          url="https://hub.docker.com/v2/repositories/${{ inputs.repository }}/tags?page_size=25&page=1&ordering=&name=$imagetag"
          exists=$(curl -s $url | jq '.results | length > 0')
          if [ "$exists" == "true" ]; then
            IMAGES+="${{ inputs.tag }}-$slug "
          fi
      done

      IMAGES=${IMAGES::-1}  # Remove the trailing space
      echo "IMAGES: $IMAGES"
      echo "images=$IMAGES" >> $GITHUB_OUTPUT
  - name: Check if there is atleast one image
    if: ${{ steps.generate_images_list.outputs.images == '[]' || steps.generate_images_list.outputs.images == '' }}
    shell: bash
    run: exit 1
  - name: Set up Docker Context for Buildx
    shell: bash
    id: buildx-context
    run: |
      docker context create builders
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
    with:
      endpoint: builders
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.DOCKER_USERNAME }}
      password: ${{ inputs.DOCKER_PASSWORD }}
  - name: Create and push manifest images
    shell: bash
    run: |
      docker buildx imagetools create --dry-run -t ${{ inputs.tag }} ${{ steps.generate_images_list.outputs.images }}
      docker buildx imagetools create -t ${{ inputs.tag }} ${{ steps.generate_images_list.outputs.images }}
