name: 'Setup'
description: 'Read and parse config files for builds'
outputs:
  platforms:
    description: "Matrix of platforms and runner to use"
    value: ${{ steps.setup_platforms.outputs.platforms }}
  tag:
    description: "Tag for the docker image"
    value: ${{ steps.set_tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: mikefarah/yq@v4.35.1
    - name: Generate platform and runner matrix from config files
      id: setup_platforms
      shell: bash
      run: |
        PLATFORMS_JSON="["

        # Extract the platforms
        platforms=$(yq e ".ethereum-genesis-generator[]" platforms.yaml)

        for platform in $platforms; do
          slug=$(echo "$platform" | tr '/' '-')
          runner=$(yq e ".\"$platform\"" runners.yaml)
          PLATFORMS_JSON+="{\"platform\":\"$platform\", \"runner\":\"$runner\", \"slug\":\"$slug\"},"
        done

        PLATFORMS_JSON="${PLATFORMS_JSON%,}]"
        echo "platforms=$PLATFORMS_JSON" >> $GITHUB_OUTPUT
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ethpandaops/ethereum-genesis-generator
        flavor: latest=auto
        tags: |
          type=raw,enable=${{ startsWith(github.ref, 'refs/tags/verkle-gen-v') }},event=tag
          type=raw,value=verkle-gen,enable=${{ github.ref == format('refs/heads/{0}', 'verkle-gen') }},event=branch
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    - name: Set tag
      id: set_tag
      shell: bash
      run: |
        echo "tag=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT


